#!/bin/bash
# sdlc-kit 설치 스크립트
# SSOT (~/.hermes/sdlc-kit/ 또는 public-knowledge-archive/sdlc-kit) → 머신 레벨 설정
#
# 하는 일:
#   1. Skills → ~/.agents/skills/ (Codex) + ~/.claude/skills/ (Claude Code)
#   2. Codex Custom Agents → ~/.codex/agents/ (subagent spawn)
#   3. Claude agents → ~/.claude/agents/ (@mention subagent)
#   4. Claude rules → ~/.claude/rules/ (always-on)
#   5. ~/.codex/AGENTS.md → symlink
#   6. ~/.claude/CLAUDE.md → @import
#
# 사용법:
#   Private SSOT:    bash ~/.hermes/sdlc-kit/scripts/install.sh
#   Public archive:  bash ~/public-knowledge-archive/sdlc-kit/scripts/install.sh
#   curl-pipe:       curl -sL https://raw.githubusercontent.com/not-for-me/public-knowledge-archive/main/sdlc-kit/scripts/install.sh | bash

set -euo pipefail

# ── Script location (path-aware: works from git clone, SSOT, or curl pipe) ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDLC_KIT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "============================================"
echo "  SDLC Harness — Machine Setup"
echo "  Source: $SDLC_KIT"
echo "============================================"

# Validate
if [ ! -f "$SDLC_KIT/AGENTS.md" ]; then
  echo "  ❌  AGENTS.md not found — wrong location?"
  exit 1
fi

# ── Skill definitions (bash 3.2 compatible) ──
SKILL_DIRS="architect tdd-expert kotlin-expert python-expert spring-expert frontend-expert database-expert api-designer devops-expert security-reviewer challenger core"

skill_name() {
  echo "sdlc-kit-$1"
}

# ── 1. Install Skills (Codex + Claude Code) ──
echo ""
echo "[1/4] Skills → Codex (~/.agents/skills/) + Claude (~/.claude/skills/)"

for dir in $SKILL_DIRS; do
  skill_name="$(skill_name "$dir")"
  src="$SDLC_KIT/skills/$dir/SKILL.md"
  [ -f "$src" ] || { echo "  ⚠  SKILL.md not found: $src — skipping"; continue; }

  # Codex
  mkdir -p "$HOME/.agents/skills/$skill_name"
  ln -sf "$src" "$HOME/.agents/skills/$skill_name/SKILL.md"

  # Claude Code
  mkdir -p "$HOME/.claude/skills/$skill_name"
  ln -sf "$src" "$HOME/.claude/skills/$skill_name/SKILL.md"

  echo "  ✅ $skill_name"
done

# ── 2. Claude Code Rules (always-on) ──
echo ""
echo "[2/4] Claude Code Rules → ~/.claude/rules/"

mkdir -p "$HOME/.claude/rules"
CORE_SRC="$SDLC_KIT/skills/core/SKILL.md"

if [ -f "$CORE_SRC" ]; then
  ln -sf "$CORE_SRC" "$HOME/.claude/rules/00-clean-code.md"
  ln -sf "$CORE_SRC" "$HOME/.claude/rules/01-git-conventions.md"
  echo "  ✅ rules/ → sdlc-kit-core"
else
  echo "  ⚠  core skill not found — skipping rules"
fi

# Clean up old agents (not needed — skills auto-discover on both platforms)
if [ -d "$HOME/.claude/agents" ]; then
  rm -f "$HOME/.claude/agents/sdlc-kit-"*.md "$HOME/.claude/agents/architect.md" "$HOME/.claude/agents/tdd-expert.md" "$HOME/.claude/agents/kotlin-expert.md" "$HOME/.claude/agents/python-expert.md" "$HOME/.claude/agents/spring-expert.md" "$HOME/.claude/agents/frontend-expert.md" "$HOME/.claude/agents/database-expert.md" "$HOME/.claude/agents/api-designer.md" "$HOME/.claude/agents/devops-expert.md" "$HOME/.claude/agents/security-reviewer.md" 2>/dev/null
  echo "  🧹 cleaned up old ~/.claude/agents/"
fi
if [ -d "$HOME/.codex/agents" ]; then
  rm -f "$HOME/.codex/agents/architect.toml" "$HOME/.codex/agents/tdd-expert.toml" "$HOME/.codex/agents/kotlin-expert.toml" "$HOME/.codex/agents/python-expert.toml" "$HOME/.codex/agents/spring-expert.toml" "$HOME/.codex/agents/frontend-expert.toml" "$HOME/.codex/agents/database-expert.toml" "$HOME/.codex/agents/api-designer.toml" "$HOME/.codex/agents/devops-expert.toml" "$HOME/.codex/agents/security-reviewer.toml" 2>/dev/null
  echo "  🧹 cleaned up old ~/.codex/agents/"
fi

# ── 3. Cross-platform AGENTS.md (Codex) ──
echo ""
echo "[3/4] Codex: ~/.codex/AGENTS.md"
mkdir -p "$HOME/.codex"
if [ -f "$HOME/.codex/AGENTS.md" ] && [ ! -L "$HOME/.codex/AGENTS.md" ]; then
  echo "  ⚠  ~/.codex/AGENTS.md exists as a regular file — backing up"
  mv "$HOME/.codex/AGENTS.md" "$HOME/.codex/AGENTS.md.bak"
fi
ln -sf "$SDLC_KIT/AGENTS.md" "$HOME/.codex/AGENTS.md"
echo "  ✅ symlinked: ~/.codex/AGENTS.md → $SDLC_KIT/AGENTS.md"

# ── 4. Claude CLAUDE.md (@import) ──
echo ""
echo "[4/4] Claude: ~/.claude/CLAUDE.md"
mkdir -p "$HOME/.claude"
CLAUDE_REL="../.codex/AGENTS.md"
cat > "$HOME/.claude/CLAUDE.md" << CLAUDE
# Claude Code Global Instructions

This file delegates to the shared cross-agent configuration.
Skills are auto-discovered from \`~/.claude/skills/\`. Do NOT edit this file directly.

\`\`\`
SSOT (private):   ~/.hermes/sdlc-kit/
Public archive:   $(git -C "$SDLC_KIT" remote get-url origin 2>/dev/null || echo "$SDLC_KIT")
\`\`\`

@import $CLAUDE_REL
CLAUDE
echo "  ✅ wrote: ~/.claude/CLAUDE.md (@import $CLAUDE_REL)"

# ── Done ──
echo ""
echo "============================================"
echo "  ✅  SDLC Harness installed!"
echo ""
echo "  Codex Skills:   ~/.agents/skills/sdlc-kit-*/"
echo "  Claude Skills:  ~/.claude/skills/sdlc-kit-*/"
echo "  Claude Rules:   ~/.claude/rules/"
echo ""
echo "  Update:  git -C $SDLC_KIT pull && bash $0"
echo "============================================"