#!/bin/bash
# sdlc-kit 설치 스크립트
# SSOT (~/.hermes/sdlc-kit/ 또는 public-knowledge-archive/sdlc-kit) → 머신 레벨 설정으로 연결
#
# 사용법:
#   Private SSOT:    bash ~/.hermes/sdlc-kit/scripts/install.sh
#   Public archive:  bash ~/public-knowledge-archive/sdlc-kit/scripts/install.sh
#   curl-pipe:       curl -sL https://raw.githubusercontent.com/not-for-me/public-knowledge-archive/main/sdlc-kit/scripts/install.sh | bash
#
# 하는 일:
#   1. ~/.codex/AGENTS.md → symlink → AGENTS.md
#   2. ~/.claude/CLAUDE.md → @import AGENTS.md
#   3. ~/.claude/rules/*  → symlink → rules/*
#   4. ~/.claude/agents/*  → symlink → agents/*

set -euo pipefail

# Detect script location (works for both local run and curl pipe)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDLC_KIT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "============================================"
echo "  SDLC Harness — Machine Setup"
echo "  Source: $SDLC_KIT"
echo "============================================"

# Validate: AGENTS.md must exist alongside
if [ ! -f "$SDLC_KIT/AGENTS.md" ]; then
  echo "  ❌  AGENTS.md not found at $SDLC_KIT/AGENTS.md"
  echo "     Is this script running from the right location?"
  exit 1
fi

# ---- 1. Codex ----
echo ""
echo "[1/4] Codex: ~/.codex/AGENTS.md"
mkdir -p "$HOME/.codex"
if [ -f "$HOME/.codex/AGENTS.md" ] && [ ! -L "$HOME/.codex/AGENTS.md" ]; then
  echo "  ⚠  ~/.codex/AGENTS.md exists as a regular file — backing up to AGENTS.md.bak"
  mv "$HOME/.codex/AGENTS.md" "$HOME/.codex/AGENTS.md.bak"
fi
ln -sf "$SDLC_KIT/AGENTS.md" "$HOME/.codex/AGENTS.md"
echo "  ✅  symlinked: ~/.codex/AGENTS.md → $SDLC_KIT/AGENTS.md"

# ---- 2. Claude Code (CLAUDE.md with @import) ----
echo ""
echo "[2/4] Claude Code: ~/.claude/CLAUDE.md"
mkdir -p "$HOME/.claude"
CLAUDE_REL="../.codex/AGENTS.md"
cat > "$HOME/.claude/CLAUDE.md" << CLAUDE
# Claude Code Global Instructions

This file delegates to the shared cross-agent configuration maintained in
\`~/.codex/AGENTS.md\`. Do NOT edit this file directly — edit the source at:

\`\`\`
SSOT (private):   ~/.hermes/sdlc-kit/AGENTS.md
Public mirror:    $(git -C "$SDLC_KIT" remote get-url origin 2>/dev/null || echo "$SDLC_KIT")
\`\`\`

@import $CLAUDE_REL
CLAUDE
echo "  ✅  wrote: ~/.claude/CLAUDE.md (@import $CLAUDE_REL)"

# ---- 3. Claude Code rules ----
echo ""
echo "[3/4] Claude Code: ~/.claude/rules/"
mkdir -p "$HOME/.claude/rules"
if [ -d "$SDLC_KIT/rules" ]; then
  for rule_file in "$SDLC_KIT/rules/"*.md; do
    [ -f "$rule_file" ] || continue
    fname=$(basename "$rule_file")
    ln -sf "$rule_file" "$HOME/.claude/rules/$fname"
    echo "  ✅  symlinked: rules/$fname"
  done
else
  echo "  ℹ️   No rules/ directory found — skipping"
fi

# ---- 4. Claude Code agents ----
echo ""
echo "[4/4] Claude Code: ~/.claude/agents/"
mkdir -p "$HOME/.claude/agents"
if [ -d "$SDLC_KIT/agents" ]; then
  for agent_file in "$SDLC_KIT/agents/"*.md; do
    [ -f "$agent_file" ] || continue
    fname=$(basename "$agent_file")
    ln -sf "$agent_file" "$HOME/.claude/agents/$fname"
    echo "  ✅  symlinked: agents/$fname"
  done
else
  echo "  ℹ️   No agents/ directory found — skipping"
fi

echo ""
echo "============================================"
echo "  ✅  SDLC Harness installed!"
echo ""
echo "  Source: $SDLC_KIT"
echo "  Codex  → ~/.codex/AGENTS.md"
echo "  Claude → ~/.claude/CLAUDE.md (@import)"
echo "  Rules  → ~/.claude/rules/"
echo "  Agents → ~/.claude/agents/"
echo ""
echo "  Update this machine:"
echo "    git -C $SDLC_KIT pull"
echo "    bash $0"
echo "============================================"